### ISSUE TITLE
Checkpoints + Training code

### ISSUE THREAD

**Issue by a-r-r-o-w** [maple-research-lab/SIM#2]
Hi folks! I'm Aryan from the HF Diffusers team and found this research work to be absolutely amazing. Thank you for the great hardwork you would have put into making SIM!

I see that the checkpoints link results in a 404 Not Found error. Will you be releasing the checkpoints at a future date or is the link incorrect?

Additionally, I would like to implement your method for learning purposes and replicating results from scratch, possibly on video models. Do you plan to release your training code as well? I'll have to admit that the paper is a bit complex for me to understand and implement, but I will try my best to create a minimal training example, so any reference would be super helpful!

Additionally, if you would like to integrate your method with Diffusers, or create a HF Space where people can generate and play with models trained using this method, I would love to help set up a communication channel via Slack!

**Comment by fetchniches** [comment]
Hi Aryan! We update our checkpoint just now. We appreciate your enthusiasm and support for our project. Currently, we do not have any plan to release our training code, here is a few reference repo which might help:
https://github.com/pkulwj1994/diff_instruct
https://github.com/mingyuanzhou/SiD

**Comment by a-r-r-o-w** [comment]
Thank you for pointing me to these works! I believe I have more than enough information to learn and replicate now
